### ISSUE TITLE
'ApplicationName' and 'Hello' strings missing

### ISSUE THREAD

**Issue by PelleRavn** [aritchie/support#1]
I recently updated the settings plugin (and the support plugin) and I started getting errors.
In the generated Resource.designer.cs file, I get two errors, every time I build, on thise lines:

```
global::Acr.Support.Android.Resource.String.ApplicationName = global::ProjectDroid.Resource.String.ApplicationName;
global::Acr.Support.Android.Resource.String.Hello = global:ProjectDroid.Resource.String.Hello;
```

The error is:

```
/Resource.designer.cs(104,104): Error CS0117: `ProjectDroid.Resource.String' does not contain a definition for `ApplicationName' (CS0117)
/Resource.designer.cs(104,104): Error CS0117: `ProjectDroid.Resource.String' does not contain a definition for `Hello' (CS0117)
```

I tracked the issue back to the commit 5 days ago where you removed the two lines from the strings.xml file: https://github.com/aritchie/support/commit/8386a991c7979fbd03aaea0ba3dbeb4830e601ed#diff-a9aefe2726403763d44c69279327596a

Is this something you can fix, and push a new Nuget version out? 
Thanks in advance :)

/Pelle

**Comment by aritchie** [comment]
This isn't an issue with the library.  They are unnecessary keys.  Clear your bin/obj files in all projects with the solution having the issue

**Comment by PelleRavn** [comment]
I already tried that several times, didn't help. 

I have a though: Did you clean before you builded the dll's that were submitted to Nuget? - We've had issues with that before with Nuget plugins.

**Comment by PelleRavn** [comment]
I just tried removing the UserDialogs (not 'settings' as I said first, my mistake), and acr.support. Installed it again and updated it to 4.1.6 (UserDialogs) and 1.0.1 (Support) and I get the same error, even that I deleted the obj/bin dirs before updating.

**Comment by BjarneFisker** [comment]
I have just updated the UserDialog plugin in my Android project and have the exact same issue with missing resources. Also tried to delete obj and bin folder without any luck.

**Comment by aritchie** [comment]
try 1.0.2 on nuget now

**Comment by PelleRavn** [comment]
1.0.2 fixed it.

Thanks a lot
