### ISSUE TITLE
Errors upgrading from 1.0.0 to 1.1.1 for Xamarin Android PCL

### ISSUE THREAD

**Issue by calbert52** [aritchie/support#2]
[Upgrade.zip](https://github.com/aritchie/support/files/210776/Upgrade.zip)
Attached is a zip containing screen captures of an error that I am getting upgrading 1.0.0 to 1.1.1 in my android pcl. The upgrade went fine for IOS.
1. Installing the upgrade produces output errors shown in screen shot "Install.Update.png".
2. After running the upgrade in visual studio 2015, it showed that it was installed.
3. Compiling my project produced the output errors shown in screen shot "Build.Error.1.png". 
4. After getting the build error, I checked out from TFS the android "Resource.Designer.cs" file.
5. Compiled my project that produced the output errors shown in screen shot "Build.Error.2.png".
6. Source code compare shows the differences found in the "Resource.Designer.cs" file after the "Resource.Designer.cs" file was checked out, and a new compile. Screen shots "Resource.Designer.cs.1" and "Resource.Designer.2.cs".

The above prevents me from using 1.1.1.

Carl Albert
calbert@timetrak.com

**Comment by aritchie** [comment]
build.error.1 & 2 have nothing to do with the library itself.  The fact that the library no longer has those resource Ids shouldn't be an issue either.  The install.update doesn't tell me anything either.  

Really, none of these have anything to do with the library itself.  Try blowing away all of your obj/bin folder if the issue persists.

**Comment by calbert52** [comment]
Allan,

After deleting all of my bin and obj folders the problem still exists. The project compiles successfully until after installing the 1.1.1 upgrade. I see you have a v2.0.0 upgrade, should I be trying that?

I am using:
Xamarin.Forms v2.1.0.6529
Xamarin.Android.Support.Design v23.0.1.3
Xamarin.Android.Support.v4 v23.0.1.3
Xamarin.Android.Support.v7.AppCompat v23.0.1.3
Xamarin.Android.Support.v7.CardView v23.0.1.3
Acr.UserDialogs v4.1.0
Acr.XamForms.UserDialogs v4.0.0
Splat v1.6.2
Plugin.CurrentActivity v1.0.1
Plugin.Permissions v1.1.7
Xam.Plugins.Settings v2.1.0
Xam.Plugin.Connectivity v2.1.2
Xam.Plugin.Geolocator v3.0.4
Newtonsoft.Json v8.0.3
Sqlite-net-pcl v1.1.1
SQLitePCL.raw v0.8.6
ZXing.Net.Mobile v2.0.4.46
ZXing.Net.Mobile v2.0.4.6
Mobilist.AdvancedTimer.Forms.Plugin v1.0.1

Carl Albert
VP Software Development
TimeTrak Systems, Inc.
Phone: (810) 984-1313 Ext. 112
Email: calbert@timetrak.commailto:calbert@timetrak.com
[cid:image001.png@01CFFF24.56A6C7F0]
www.timetrak.comhttp://www.timetrak.com

**Comment by aritchie** [comment]
Uninstall all Acr libraries.  Since you are using xamarin forms, install 4.2.1 of Acr.userdialogs (not latest) from Nuget
